challenges/urls.py
from django.urls import path

from . import views

app_name='challenges'


urlpatterns = [
        path('', views.index, name='challenges'),
        path('<int:order>/', views.challengeDetails, name='challengeDetails'),
        path('validation/', views.validation, name='validation'),
        path('passwordSecurity', views.passwordSecurity, name='passwordSecurity'),
        path('supersecure', views.security, name='supersecure'),
        path('securityValidation', views.securityValidation, name='securityValidation'),
        path('secure', views.secure, name='secure'),
        path('cookieValidation/', views.cookieValidation, name='cookieValidation'),
        path('adminLogin/', views.adminLogin, name='adminLogin'),
        path('completed/', views.completed, name='completed'),
        path('allChallenges/', views.allChallenges, name='allChallenges'),
        path('anotherRequest/', views.anotherRequest, name='anotherRequest/'),
        path('l33t/', views.hardChallenges, name='hardChallenges'),
        path('l33t/deleteServer/', views.deleteServer, name='deleteServer'),
        path('l33t/adminLogin/', views.hardAdminLogin, name='hardAdminLogin'),
]

chroot/urls.py
from django.urls import path

from . import views

app_name='chroot'

urlpatterns = [
        path('<username>/', views.userSpecificIndex, name='userSpecificIndex'),

    ]

hacking_challenge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


# TODO: seperate out security and cookieValidation into its own apps
urlpatterns = [
    path('admin/', admin.site.urls),
    path('challenges/', include('challenges.urls')),
    path('playground/', include('playground.urls')),
    path('', include('homepage.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('login/', include('loginSignup.urls')),
    path('settings/', include('settings.urls')),
    path('LoneWolf/', include('wolfIncorporated.urls')),
    path('WhiteBox/', include('whiteBoxHacking.urls')),
    path('Phenomenal.png', RedirectView.as_view(url=staticfiles_storage.url('Phenomenal.png'))),
    path('2Down.PNG', RedirectView.as_view(url=staticfiles_storage.url('2Down.PNG'))),
    path('3Down.PNG', RedirectView.as_view(url=staticfiles_storage.url('3Down.PNG'))),
    path('Ascended.PNG', RedirectView.as_view(url=staticfiles_storage.url('Ascended.PNG'))),
    path('Breathtaking.PNG', RedirectView.as_view(url=staticfiles_storage.url('Breathtaking.PNG'))),
    path('ClassFirst.PNG', RedirectView.as_view(url=staticfiles_storage.url('ClassFirst.PNG'))),
    path('ClassSecond.PNG', RedirectView.as_view(url=staticfiles_storage.url('ClassSecond.PNG'))),
    path('ClassThird.PNG', RedirectView.as_view(url=staticfiles_storage.url('ClassThird.PNG'))),
    path('Completion.PNG', RedirectView.as_view(url=staticfiles_storage.url('Completion.PNG'))),
    path('DeadEye.PNG', RedirectView.as_view(url=staticfiles_storage.url('DeadEye.PNG'))),
    path('Flawless.PNG', RedirectView.as_view(url=staticfiles_storage.url('Flawless.PNG'))),
    path('GoldenEye.PNG', RedirectView.as_view(url=staticfiles_storage.url('GoldenEye.PNG'))),
    path('PlayingWithFire.PNG', RedirectView.as_view(url=staticfiles_storage.url('PlayingWithFire.PNG'))),
    path('Tenacious.PNG', RedirectView.as_view(url=staticfiles_storage.url('Tenacious.PNG'))),
    path('Committed.PNG', RedirectView.as_view(url=staticfiles_storage.url('Committed.PNG'))),
    path('BotStatus.PNG', RedirectView.as_view(url=staticfiles_storage.url('BotStatus.PNG'))),
    path('UOKBro.PNG', RedirectView.as_view(url=staticfiles_storage.url('UOKBro.PNG'))),
    path('Unstoppable.PNG', RedirectView.as_view(url=staticfiles_storage.url('Unstoppable.PNG'))),
    path('Upstoppable.PNG', RedirectView.as_view(url=staticfiles_storage.url('Unstoppable.PNG'))),
    path('Unforgettable.PNG', RedirectView.as_view(url=staticfiles_storage.url('Unforgettable.PNG'))),
    path('EarlyBird.PNG', RedirectView.as_view(url=staticfiles_storage.url('EarlyBird.PNG'))),
    path('chroot/', include('chroot.urls')),
    path('customAdmin/', include('customAdmin.urls')),
    ]

challenges/models.py
from django.db import models


class Challenge(models.Model):
    flag = models.CharField(max_length=50)
    title = models.CharField(max_length=20, default='Challenge')
    description = models.CharField(max_length=300, default='A very nice description')
    order = models.IntegerField()
    templateValue = models.IntegerField(default=-1)
    hidden = models.BooleanField(default=False)
    pointValue = models.IntegerField(default=10)
    optionalChallenge = models.BooleanField(default=False)
    difficultyIndicator = models.CharField(max_length=20, default='Easy')
    challengeSeries = models.CharField(max_length=50, default="Basic")
    totalIncorrectGuesses = models.IntegerField(default=0)
    numberOfUsersOnThisChallenge = models.IntegerField(default=0)


    class Meta:
        ordering = ['order']


    def __str__(self):
        return str(f'Challenge {self.order}')



# Having hint seperate will allow easier adding of new hints to each specific challenge

class Hint(models.Model):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    hint = models.TextField()


    def __str__(self):
        return str(self.challenge.title)

challenges/views.py
from django.shortcuts import render, get_object_or_404
from .models import Challenge, Hint
from loginSignup.models import CustomUser
from customAdmin.models import AssignmentDates
from achievements.models import Achievements
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import json
from datetime import datetime, timedelta


@login_required()
def index(request):
    easyChallenges = Challenge.objects.filter(
        difficultyIndicator="Easy").order_by('order')
    moderateChallenges = Challenge.objects.filter(
        difficultyIndicator="Moderate").order_by('order')
    hardChallenges = Challenge.objects.filter(
        difficultyIndicator="Hard").order_by('order')
    leetChallenges = Challenge.objects.filter(
        difficultyIndicator="l33t").order_by('order')
    customUser = CustomUser.objects.get(user=request.user.id)
    data = json.loads(customUser.challenges)
    count = 0
    easyCompleted = 0
    currentEasyChallenge = easyChallenges[0].order
    foundCurrentChallenge = False
    completedChallenges = customUser.completedChallenges
    completedRequiredChallenges = customUser.completedRequiredChallenges
    print(completedRequiredChallenges)
    numChallenges = customUser.numChallenges
    numRequiredChallenges = customUser.numRequiredChallenges
    isAdmin = customUser.admin

    for challenge in easyChallenges:
        challenge.hidden = data[count]['hidden']
        challenge.completed = data[count]['completed']
        challenge.data = data[count]
        if data[count]['completed'] == 'true':
            easyCompleted += 1
            if easyCompleted != len(easyChallenges):
                if data[count + 1]['completed'] == 'false':
                    currentEasyChallenge = easyChallenges[count + 1].order
            else:
                currentEasyChallenge = 'completed'

        count += 1

        if easyCompleted < len(easyChallenges) - 3:
            moderateLocked = 'true'
        else:
            moderateLocked = 'false'

        if easyCompleted == len(easyChallenges):
            pass
            # hardLocked = 'false'
            # hardChallengesCount = len(hardChallenges)
            # for i in range(hardChallengesCount):
            #     data[len(moderateChallenges) + len(easyChallenges) + i]['hidden'] = 'false'
            # customUser.challenges = json.dumps(data)
            # customUser.save()

        else:
            hardLocked = 'true'
            leetLocked = 'true'
    if moderateLocked == 'false':
        data[len(easyChallenges)]['hidden'] = 'false'
        customUser.challenges = json.dumps(data)
        customUser.save()

    moderateCompleted = 0
    moderateFound = False

    for challenge in moderateChallenges:
        challenge.hidden = data[count]['hidden']
        challenge.completed = data[count]['completed']
        challenge.data = data[count]
        if data[count]['completed'] == 'true':
            moderateCompleted += 1
            if moderateCompleted != len(moderateChallenges):
                if data[count + 1]['completed'] == 'false':
                    currentModerateChallenge = moderateChallenges[count - len(
                        easyChallenges) + 1].order
                    moderateFound = True
            else:
                currentModerateChallenge = 'completed'
        else:
            if not moderateFound:
                currentModerateChallenge = moderateChallenges[0].order
        count += 1

    if moderateCompleted == len(moderateChallenges):
        hardLocked = 'false'
        leetLocked = 'false'
        hardChallengesCount = len(hardChallenges)
        for i in range(hardChallengesCount):
            data[len(moderateChallenges) +
                 len(easyChallenges) + i]['hidden'] = 'false'
        for i in range(len(leetChallenges)):
            data[len(moderateChallenges) + len(easyChallenges) +
                 len(hardChallenges) + i]['hidden'] = 'false'
        customUser.challenges = json.dumps(data)
        customUser.save()

    hardCompleted = 0
    hardFound = False

    for challenge in hardChallenges:
        challenge.hidden = data[count]['hidden']
        challenge.completed = data[count]['completed']
        challenge.data = data[count]
        if data[count]['completed'] == 'true':
            hardCompleted += 1
            if hardCompleted == len(hardChallenges):
                currentHardChallenge = 'completed'
                hardFound = True
        else:
            if not hardFound:
                currentHardChallenge = hardChallenges[0].order + 2
        count += 1

    leetCompleted = 0
    leetFound = False
    currentLeetChallenge = ''

    for challenge in leetChallenges:
        challenge.hidden = data[count]['hidden']
        challenge.completed = data[count]['completed']
        challenge.data = data[count]
        if data[count]['completed'] == 'true':
            leetCompleted += 1
            if leetCompleted == len(leetChallenges):
                currentLeetChallenge = 'completed'
                leetFound = True
            else:
                if not leetFound:
                    currentLeetChallenge = leetChallenges[0].order
        count += 1

    # needs isAdmin, completedChallenges, numChallenges, numRequiredChallenges, completedRequiredChallenges
    return render(request, 'challenges/index.html', {
        'isAdmin': isAdmin,
        'completedChallenges': completedChallenges,
        'numChallenges': numChallenges,
        'numRequiredChallenges': numRequiredChallenges,
        'completedRequiredChallenges': completedRequiredChallenges,
        'easyChallenges': easyChallenges,
        'moderateChallenges': moderateChallenges,
        'hardChallenges': hardChallenges,
        'leetChallenges': leetChallenges,
        'easyCompleted': easyCompleted,
        'moderateCompleted': moderateCompleted,
        'hardCompleted': hardCompleted,
        'leetCompleted': leetCompleted,
        'moderateLocked': moderateLocked,
        'hardLocked': hardLocked,
        'leetLocked': leetLocked,
        'currentEasyChallenge': currentEasyChallenge,
        'currentModerateChallenge': currentModerateChallenge,
        'currentHardChallenge': currentHardChallenge,
        'currentLeetChallenge': currentLeetChallenge,
    })


@login_required()
def validation(request):
    if (request.method == "POST"):
        json_response = []
        allGood = True
        success = False

        if (AssignmentDates.objects.all()):
            currentTime = datetime.now().time()
            currentDate = datetime.today().date()
            openDate = AssignmentDates.objects.get(description="open")
            closeDate = AssignmentDates.objects.get(description="closed")

            if currentDate < openDate.date or currentDate > closeDate.date:
                allGood = False

            if currentDate > openDate.date and currentDate < closeDate.date:
                if (currentTime > closeDate.time and currentTime == closeDate.date) or (currentTime < openDate.time and currentTime == openDate.date):
                    allGood = False

        challenge_id = int(request.POST['challenge_id'])
        challenge = Challenge.objects.get(order=challenge_id)
        customUser = CustomUser.objects.get(user=request.user.id)

        # Create the JSON object
        ########################
        if (challenge.flag == request.POST['passcode'].strip()):
            success = True
            data = json.loads(customUser.challenges)
            incorrectPerChallengeData = json.loads(
                customUser.incorrectPerChallenge)

            if data[challenge_id]['completed'] != 'true' and allGood:
                customUser.completedChallenges += 1

                if not Challenge.objects.get(order=challenge_id).optionalChallenge:
                    # This doesn't add to their score after the assignment closes
                    if allGood:
                        customUser.completedRequiredChallenges += 1

                customUser.correctInARow += 1
                customUser.percentComplete = (
                    customUser.completedChallenges / customUser.numRequiredChallenges) * 100
                if customUser.percentComplete > 100:
                    customUser.percentComplete = 100

                data[challenge_id-1]['completed'] = 'true'
                if not challenge_id > len(Challenge.objects.all()) - 1:
                    data[challenge_id]['hidden'] = 'false'

                if (customUser.correctInARow % 8) == 2:
                    achievements = json.loads(customUser.achievements)
                    achievements.append('2 down')
                    customUser.achievements = json.dumps(achievements)

                if (customUser.correctInARow % 8) == 3:
                    achievements = json.loads(customUser.achievements)
                    achievements.append('3 down')
                    customUser.achievements = json.dumps(achievements)

                if (customUser.correctInARow % 8) == 4:
                    achievements = json.loads(customUser.achievements)
                    achievements.append('Breathtaking')
                    customUser.achievements = json.dumps(achievements)

                if (customUser.correctInARow % 8) == 5:
                    achievements = json.loads(customUser.achievements)
                    achievements.append('Phenomenal')
                    customUser.achievements = json.dumps(achievements)

                if (customUser.correctInARow % 8) == 6:
                    achievements = json.loads(customUser.achievements)
                    achievements.append('Unstoppable')
                    customUser.achievements = json.dumps(achievements)

                if (customUser.correctInARow % 8) == 7:
                    achievements = json.loads(customUser.achievements)

challenges/templates/challenges/11.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <title>Brute Force </title>
        <script src="{% static 'homepage/node_modules/vue/dist/vue.global.prod.js' %}"></script>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/hardChallenges.css' %}">
        <script type="module" defer src="{% static 'challenges/levelDescriptionHard.js' %}"></script>
        <link rel="stylesheet" href="{% static 'challenges/incorrectIndicator.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/challengeBar.css' %}">
    </head>

    <body>
        <div class="movedDownForChallengeBar">
            <div class="levelNumber"> Challenge {{ challenge.order }} </div>

            <div class="levelDescription"> {{challenge.description }} </div>

            <div id="formAndHints">
                <div v-if="isLoaded">
                    <div id='challengeBar'>
                        <div class="navbar" id="myNavbar">
                            <a class="" href="/challenges/l33t/"> <i class="fa fa-arrow-left rightSpacing" aria-hidden="true" id="homeIcon"></i> It's Too Difficult! </a>
                        </div>
                    </div>

                    <div :hidden= "isInvisible" id="hints" class="popup_hints">
                        <span class="helper"></span>
                        <div>
                            <div class="popupCloseButton" @click=getHints()>&times;</div>
                            <p><strong> Requires Knowledge of: </strong></p>
                            <ul id="hintsList">
                                {% for hint in challenge.hint_set.all %}
                                <li> {{ hint.hint }} </li>
                                <br> 
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>



                <form action="../validation/" id="passcodeForm" method="POST" >


                    <input v-model="passcodeInput" id="passcodeValidation" name="passcodeValidation" placeholder="password">
                    <button type="button" class="customButtom" id="submitButton" @click=validateInput()> Submit </button>
                    <input hidden id="challenge_id" name='challenge_id' value = {{ challenge.order }}>
                    <input hidden id="csrf_token" value = {{ csrf_token }}>
                    <button type="button"   id="hintButton" @click=getHints()> View Hint </button>
                    <br>
                    <div :hidden= "isIncorrectHidden" id="incorrectIndicator">
                        <div id="incorrectText"> Incorrect! </div>
                    </div>
                    <div :hidden= "isCorrectHidden" id="correctIndicator">
                        <div id="correctText"> Correct! </div>
                    </div>
                    <div :hidden= "isAssignmentClosedHidden" id="incorrectIndicator">
                        <div id="incorrectText"> Correct! However, Assignment is Currently Closed and no further progress will count for your grade! </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="loginForm">
            <form action="../l33t/adminLogin/" method="POST" autocomplete="off">
                {% csrf_token %}
                <input class="darkFormEntry"  type="text" name="username" placeholder="email">
                <input class="darkFormEntry" type="password" name="password" placeholder="password">
                <button type="submit" id='submitButtonAdmin'> Login </button>
            </form>
        </div>

        <div class="small-text centered"> *Note. Upon getting the email and password, enter the information above to "log in" </div>


    </body>


</html>

challenges/templates/challenges/12.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <title>BECOME AN ADMIN </title>

        <script type="module" defer src="{% static 'challenges/levelDescriptionHard.js' %}"></script>
        <script src="{% static 'homepage/node_modules/vue/dist/vue.global.prod.js' %}"></script>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/hardChallenges.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/incorrectIndicator.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/challengeBar.css' %}">
    </head>

    <body>
        <div class="movedDownForChallengeBar">
            <div class="levelNumber"> Challenge {{ challenge.order }} </div>

            <div class="levelDescription"> {{challenge.description }} </div>

            <div id="formAndHints">
                <div v-if="isLoaded">
                    <div id='challengeBar'>
                        <div class="navbar" id="myNavbar">
                            <a class="" href="/challenges/l33t/"> <i class="fa fa-arrow-left rightSpacing" aria-hidden="true" id="homeIcon"></i> It's Too Difficult! </a>
                        </div>
                    </div>

                    <div :hidden= "isInvisible" id="hints" class="popup_hints">
                        <span class="helper"></span>
                        <div>
                            <div class="popupCloseButton" @click=getHints()>&times;</div>
                            <p><strong> Requires Knowledge of: </strong></p>
                            <ul id="hintsList">
                                {% for hint in challenge.hint_set.all %}
                                <li> {{ hint.hint }} </li>
                                <br> 
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>

                {% if admin %}
                    <div id="adminFlag">Flag: {{ adminFlag }} </div>
                {% endif %}



                <form action="../validation/" id="passcodeForm" method="POST" >


                    <input v-model="passcodeInput" id="passcodeValidation" name="passcodeValidation" placeholder="password">
                    <button type="button" class="customButtom" id="submitButton" @click=validateInput()> Submit </button>
                    <input hidden id="challenge_id" name='challenge_id' value = {{ challenge.order }}>
                    <input hidden id="csrf_token" value = {{ csrf_token }}>
                    <button type="button"   id="hintButton" @click=getHints()> View Hint </button>
                    <br>
                    <div :hidden= "isIncorrectHidden" id="incorrectIndicator">
                        <div id="incorrectText"> Incorrect! </div>
                    </div>
                    <div :hidden= "isCorrectHidden" id="correctIndicator">
                        <div id="correctText"> Correct! </div>
                    </div>
                    <div :hidden= "isAssignmentClosedHidden" id="incorrectIndicator">
                        <div id="incorrectText"> Correct! However, Assignment is Currently Closed and no further progress will count for your grade! </div>
                    </div>
                </form>
            </div>
        </div>



    </body>


</html>

challenges/templates/challenges/15.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">

        <script src="{% static 'homepage/node_modules/vue/dist/vue.global.prod.js' %}"></script>
        <script type="module" defer src="{% static 'challenges/levelDescription.js' %}"></script>
        <link rel="stylesheet" href="{% static 'challenges/popupStyle.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/incorrectIndicator.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/challengeBar.css' %}">
        <title> Challenge {{ challenge.order }} </title>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">

    </head>

    <body>

        {% include 'challenges/levelDescriptionTemplate.html' %}


        <div id='supplementalDescription'> As you go along, the flag will be clearly given to you. <br> Make sure you enter them in as soon as you get them, as some are not repeatable :) </div>

        <div class="loneWolfDiv">
            <a class="loneWolfLink" href="../../LoneWolf/"> 
                <img class="wolfLogo" src="{% static 'challenges/loneWolf.jpeg' %}"/> 
                <br>
                Lone Wolf 
            </a>
        </div>

    </body>


</html>

challenges/templates/challenges/3.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <script src="{% static 'homepage/node_modules/vue/dist/vue.global.prod.js' %}"></script>
        <script type="module" defer src="{% static 'challenges/levelDescription.js' %}"></script>
        <link rel="stylesheet" href="{% static 'challenges/popupStyle.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/incorrectIndicator.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/challengeBar.css' %}">
        <title> Challenge {{ challenge.order }} </title>
        <script defer src="{% static 'challenges/rh.js' %}"></script>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">
    </head>

    <body>

        {% include 'challenges/levelDescriptionTemplate.html' %}

        <div id="challenge">[% nothingJustForWarning %]</div>


    </body>



</html>

challenges/templates/challenges/5.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <script src="{% static 'homepage/node_modules/vue/dist/vue.global.prod.js' %}"></script>
        <script type="module" defer src="{% static 'challenges/levelDescription.js' %}"></script>
        <link rel="stylesheet" href="{% static 'challenges/popupStyle.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/incorrectIndicator.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/challengeBar.css' %}">
        <title> Challenge {{ challenge.order }} </title>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">
        <script src=" {% static 'challenges/level5.js' %}"></script>
    </head>

    <body>


        {% include 'challenges/levelDescriptionTemplate.html' %}




    </body>


</html>

challenges/templates/challenges/9.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <script src="{% static 'homepage/node_modules/vue/dist/vue.global.prod.js' %}"></script>
        <script type="module" defer src="{% static 'challenges/levelDescription.js' %}"></script>
        <link rel="stylesheet" href="{% static 'challenges/popupStyle.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/incorrectIndicator.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/challengeBar.css' %}">
        <title> Challenge {{ challenge.order }} </title>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">

    </head>

    <body>

        {% include 'challenges/levelDescriptionTemplate.html' %}
        <div id="theSolution"> 
            <a href="https://www.youtube.com/watch?v=Ye8mB6VsUHw"> The Solution </a>
        </div>

        <div class="loneWolfDiv">
            <a class="loneWolfLink" href="../../WhiteBox/"> 
                <img class="wolfLogo" src="{% static 'whiteBoxHacking/whitebox.png' %}"/> 
                <br>
                White Box  
            </a>
            <div class="whiteBoxDetails"> Recent security flaws were found in this website. Use it to solve challenges 7-10. <br> Think you know how to solve this one? Submit below for flag.
        </div>




        <div class="loginForm">
            <form action="/WhiteBox/cookieValidation" method="POST" autocomplete="off">
                {% csrf_token %}
                <input class="formEntry bash" type="password" name="password" placeholder="Cookie go CRUNCH!" />
                <button type="submit" class="new-button">Validate Cookie</button>
            </form>
        </div>



    </body>


</html>

challenges/templates/challenges/challenge0.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">
    </head>

    <body>

        {% include 'challenges/levelDescriptionTemplate.html' %}

        <div hidden><p> Just in case I forget... This was the most popular password the year the first avengers movie came out. </div>


    </body>
</html>

challenges/templates/challenges/challenge1.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">

    </head>

    <body>

        {% include 'challenges/levelDescriptionTemplate.html' %}
        
        <div class="challenge-desc">
            <div class="layer-down">
                <div class="some-stuff">
                </div>
                <span class="challenges">
                    <div class="some-stuff">
                    </div>
                    <!-- the password is {{challenge.flag}} -->
            </div>
        </div>
    </body>


</html>

challenges/templates/challenges/challenge11.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <script src="https://unpkg.com/vue@next"></script>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">

    </head>

    <body>

        {% include 'challenges/levelDescriptionTemplate.html' %}

        <div style="align: center; text-align: center; font-size: 16px; margin-top: 16px;"> qCGeFfekiW! </div>



    </body>


</html>

challenges/templates/challenges/challenge12.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <script src="https://unpkg.com/vue@next"></script>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">

    </head>

    <body>

        {% include 'challenges/levelDescriptionTemplate.html' %}



    </body>


</html>

challenges/templates/challenges/challenge4.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <script src="https://unpkg.com/vue@next"></script>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'challenges/style.css' %}">
        <script defer src="{% static 'challenges/dp.js' %}"></script>
    </head>

    <body>


        {% include 'challenges/levelDescriptionTemplate.html' %}

        <div hidden id="passwrd">
            <div> {{challenge.flag}} </div>
        </div>


    </body>


</html>