chroot/urls.py
from django.urls import path

from . import views

app_name='chroot'

urlpatterns = [
        path('<username>/', views.userSpecificIndex, name='userSpecificIndex'),

    ]

hacking_challenge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


# TODO: seperate out security and cookieValidation into its own apps
urlpatterns = [
    path('admin/', admin.site.urls),
    path('challenges/', include('challenges.urls')),
    path('playground/', include('playground.urls')),
    path('', include('homepage.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('login/', include('loginSignup.urls')),
    path('settings/', include('settings.urls')),
    path('LoneWolf/', include('wolfIncorporated.urls')),
    path('WhiteBox/', include('whiteBoxHacking.urls')),
    path('Phenomenal.png', RedirectView.as_view(url=staticfiles_storage.url('Phenomenal.png'))),
    path('2Down.PNG', RedirectView.as_view(url=staticfiles_storage.url('2Down.PNG'))),
    path('3Down.PNG', RedirectView.as_view(url=staticfiles_storage.url('3Down.PNG'))),
    path('Ascended.PNG', RedirectView.as_view(url=staticfiles_storage.url('Ascended.PNG'))),
    path('Breathtaking.PNG', RedirectView.as_view(url=staticfiles_storage.url('Breathtaking.PNG'))),
    path('ClassFirst.PNG', RedirectView.as_view(url=staticfiles_storage.url('ClassFirst.PNG'))),
    path('ClassSecond.PNG', RedirectView.as_view(url=staticfiles_storage.url('ClassSecond.PNG'))),
    path('ClassThird.PNG', RedirectView.as_view(url=staticfiles_storage.url('ClassThird.PNG'))),
    path('Completion.PNG', RedirectView.as_view(url=staticfiles_storage.url('Completion.PNG'))),
    path('DeadEye.PNG', RedirectView.as_view(url=staticfiles_storage.url('DeadEye.PNG'))),
    path('Flawless.PNG', RedirectView.as_view(url=staticfiles_storage.url('Flawless.PNG'))),
    path('GoldenEye.PNG', RedirectView.as_view(url=staticfiles_storage.url('GoldenEye.PNG'))),
    path('PlayingWithFire.PNG', RedirectView.as_view(url=staticfiles_storage.url('PlayingWithFire.PNG'))),
    path('Tenacious.PNG', RedirectView.as_view(url=staticfiles_storage.url('Tenacious.PNG'))),
    path('Committed.PNG', RedirectView.as_view(url=staticfiles_storage.url('Committed.PNG'))),
    path('BotStatus.PNG', RedirectView.as_view(url=staticfiles_storage.url('BotStatus.PNG'))),
    path('UOKBro.PNG', RedirectView.as_view(url=staticfiles_storage.url('UOKBro.PNG'))),
    path('Unstoppable.PNG', RedirectView.as_view(url=staticfiles_storage.url('Unstoppable.PNG'))),
    path('Upstoppable.PNG', RedirectView.as_view(url=staticfiles_storage.url('Unstoppable.PNG'))),
    path('Unforgettable.PNG', RedirectView.as_view(url=staticfiles_storage.url('Unforgettable.PNG'))),
    path('EarlyBird.PNG', RedirectView.as_view(url=staticfiles_storage.url('EarlyBird.PNG'))),
    path('chroot/', include('chroot.urls')),
    path('customAdmin/', include('customAdmin.urls')),
    ]

loginSignup/urls.py
from django.urls import path

from . import views


app_name ='loginSignup'

urlpatterns = [
        path('', views.index, name='login'),
        path('signUp', views.signUp, name='signUp'),
        path('signIn', views.signIn, name='signIn'),

]

loginSignup/models.py
from django.db import models
from challenges.models import Challenge
from django.contrib.auth.models import User


# Create your models here.

class CustomUser(models.Model):
    numChallenges = models.IntegerField(default=0)
    numRequiredChallenges = models.IntegerField(default=0)
    completedChallenges = models.IntegerField(default=0)
    completedRequiredChallenges = models.IntegerField(default=0)
    challenges = models.JSONField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    admin = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    customText = models.TextField(default="", blank=True)
    numTotalIncorrectGuesses = models.IntegerField(default=0)
    incorrectPerChallenge = models.JSONField()
    achievements = models.JSONField()
    correctInARow = models.IntegerField(default=0)
    completedAllChallenges = models.BooleanField(default=False)
    percentComplete = models.FloatField(default=0.00)
    completedAllRequired = models.BooleanField(default=False)
    hasYouOkayBro = models.BooleanField(default=False)

    class Meta:
        ordering = ['last_name']




    def __str__(self):
        return f" {self.user.first_name} {self.user.last_name} { round(((self.completedRequiredChallenges / self.numRequiredChallenges) * 100), 2) }%"

loginSignup/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist


class RegistrationForm(forms.Form):
    firstName = forms.CharField(label="firstName", max_length=30, widget=forms.TextInput (attrs={'placeholder': 'First Name', 'class': 'formEntryLogin split'}))
    lastName = forms.CharField(label="lastName", max_length=30, widget= forms.TextInput (attrs={'placeholder': 'Last Name', 'class': 'formEntryLogin split'}))
    username = forms.CharField(label="Username", max_length=30, widget=forms.TextInput (attrs={'placeholder': 'Username', 'class': 'formEntryLogin entry'}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput (attrs={'placeholder': 'Email', 'class': 'formEntryLogin entry'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput (attrs={'placeholder': 'Password', 'class': 'formEntryLogin split'}))
    confirm_password = forms.CharField(label="Confirm Password", widget=forms.PasswordInput (attrs={'placeholder': 'Confirm Password', 'class': 'formEntryLogin split' }))


    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True

    def verify_password(self):
        if 'password' in self.cleaned_data:
            password = self.cleaned_data['password']
            confirm_password = self.cleaned_data['confirm_password']
            if password == confirm_password:
                return confirm_password

        raise forms.ValidationError('Passwords do not match.')

    def verify_unique_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$<', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters')
        if User.objects.filter(username=self.cleaned_data['username']).exists():
            return username
        else:
            raise forms.ValidationError('Username is already taken.')

loginSignup/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from .forms import RegistrationForm
from .models import CustomUser
from challenges.models import Challenge
import json
from datetime import datetime, timedelta
from customAdmin.models import AssignmentDates


def index(request):
    return render(request, 'loginSignup/signinScreen.html')


def signIn(request):
    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect('../')
    else:
        return render(request, 'loginSignup/signinScreen.html', {'error_message': 'Incorrect Login'})


def signUp(request):
    form = RegistrationForm()

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            if not User.objects.filter(username=form.cleaned_data['username']).exists():
                if form.cleaned_data['password'] == form.cleaned_data['confirm_password']:

                    email = form.cleaned_data['email']
                    if not email.endswith('usu.edu'):
                        messages.error(request, message="Use a usu.edu email")
                        return render(request, 'loginSignup/signUpScreen.html', {'form': form})

                    userCreated = User.objects.create_user(
                        username=form.cleaned_data['username'],
                        password=form.cleaned_data['password'],
                        email=form.cleaned_data['email'],
                        first_name=form.cleaned_data['firstName'],
                        last_name=form.cleaned_data['lastName'],
                    )

                    challengesJSON = []
                    incorrectPerChallenge = []
                    JSONAchievements = json.dumps([])

                    try:
                        openTime = AssignmentDates.objects.get(
                            description="open")

                        if (openTime.date + timedelta(days=3) > datetime.now().date()):
                            achievements = json.loads(JSONAchievements)
                            achievements.append('Early Bird')
                            JSONAchievements = json.dumps(achievements)

                    except:
                        pass

                    for i in range(Challenge.objects.all().count()):
                        if i != 0:
                            challenge = {f'challenge{i + 1}': f'{i + 1}',
                                         'hidden': 'true', 'completed': 'false'}
                        else:
                            challenge = {f'challenge{i + 1}': f'{i + 1}',
                                         'hidden': 'false', 'completed': 'false'}

                        incorrectness = {
                            f'challenge{i + 1}': f'{i + 1}', 'numberIncorrect': '0'}

                        challengesJSON.append(challenge)
                        incorrectPerChallenge.append(incorrectness)

                    JSONchallenges = json.dumps(challengesJSON)
                    JSONIncorrect = json.dumps(incorrectPerChallenge)
                    numberRequiredChallenges = Challenge.objects.all().filter(
                        optionalChallenge=False).count()

                    customUser = CustomUser(numChallenges=Challenge.objects.all().count(), numRequiredChallenges=numberRequiredChallenges, completedChallenges=0, challenges=JSONchallenges, incorrectPerChallenge=JSONIncorrect, user=userCreated,
                                            first_name=form.cleaned_data['firstName'], last_name=form.cleaned_data['lastName'], achievements=JSONAchievements, customText="Look at who is too cool for flavor text or something! Psh! (Ironically, this is your flavor text")

                    userCreated.save()
                    customUser.save()

                    login(request, userCreated)
                    return HttpResponseRedirect('../../')
                else:
                    messages.error(request, message="Passwords do not match")
            else:
                messages.error(
                    request, message='Username is already taken. Please use a different username')
    return render(request, 'loginSignup/signUpScreen.html', {'form': form})

loginSignup/templates/loginSignup/signUpScreen.html
<!DOCTYPE html>

<html>

    <head>
        {% load static %}
        <title> CS2610 Create Account </title>
        <meta charset="utf-8">
        <script src="{% static 'homepage/node_modules/vue/dist/vue.global.prod.js' %}"></script>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'loginSignup/style.css' %}">
    </head>

    <body>
        <div class="title"> CS 2610 <br> <div id="hackingChallengeTitle"> Hacking Challenge </div> </div>
        


        {% if form.errors %}
            {% for errors in form.errors %}
                <div class="errors">
                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ errors }} is required!
                </div>
            {% endfor %}

        {% endif %}
        
        {% if messages %}
            {% for message in messages %}
                <div class="errors">
                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ message }}!
                </div>
            {% endfor %}

        {% endif %}

        <div class="wrapperCreate">
            <div class="createAccountForm">
                <div class="createAccountText"> Create your Account </div>
                <form action="{% url 'loginSignup:signUp' %}" method="POST" autocomplete="off">
                    {% csrf_token %}
                    <div class='sameLine'>
                        {{ form.firstName }} 
                         {{ form.lastName }} 
                    </div>
                    {{ form.username }} 
                    {{ form.email }} 
                    <div class="sameLine" id='password'>
                        {{ form.password }}  
                        {{ form.confirm_password }}  
                    </div>
                    {{ forms.as_p }}


                <div class="bottomButtonHolder">
                    <div class="signUpText">
                        <a class="linkText" href="../"> Sign In Instead </a>
                    </div>
                    <div class="whiteSpaceCreate"> </div>
                    <button id="submitButton" type="submit"> CREATE ACCOUNT </button>
                </div>
                </form>

            </div>
            <div id="accountInformation">
                * Use your USU email<br>
                * Use your real name. Submissions will be graded on that <br>
                * Username can be whatever and will be your login <br>
            </div>
        </div>

    </body>

   <script>
        var password = document.querySelector("#password")
        var confirm_password = document.querySelector("#confirmPassword")

        function validatePassword() {
            if (password.value != confirm_password.value) {
                confirm_password.setCustomValidity("Passwords Don't Match");
            } else {
                confirm_password.setCustomValidity("");
            }
        }

        password.onchange = validatePassword;
        confirm_password.onkeyup = validatePassword;


   </script>



</html>

loginSignup/templates/loginSignup/signinScreen.html
<!DOCTYPE html>

<html>

    <head>
        {% load static %}
        <title> CS2610 Login </title>
        <meta charset="utf-8">
        <script src="{% static 'homepage/node_modules/vue/dist/vue.global.prod.js' %}"></script>
        <link rel="stylesheet" href="{% static 'homepage/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'loginSignup/style.css' %}">
    </head>

    <body>
        <div class="title"> CS 2610 <br> <div id="hackingChallengeTitle"> Hacking Challenge </div> </div>
        

        {% if error_message %}
            <div class="errors">
                <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ error_message }}
            </div>
        {% endif %}

        <div class="wrapper">
            <div class="signinForm">
                <div class="createAccountText"> Login </div>
                <form action="{% url 'loginSignup:signIn' %}" method="POST" autocomplete="off">
                    {% csrf_token %}
                    <input class="formEntryLogin" id="usernameLogin" type="text" name="username" placeholder="Username" required><br>
                    <input class="formEntryLogin" id="passwordLogin" type="password" name="password" placeholder="Password" required><br>

                    <div class="bottomButtonHolder">
                        <div class="signInText">
                            <a class="linkText" href="signUp">
                                <div> Create an Account </div>
                            </a>
                        </div>
                        <div class="whiteSpace"> </div>
                        <button id="submitButtonLogin" type="submit"> SIGN IN </button>
                    </div>
                </form>
            </div>
        </div>




    </body>


</html>